<?php if($menu = $this->getMenu()){ ?>
<?php
$data = $this->helper("\Ves\Megamenu\Helper\Data");
$layout = $this->getData('layout');
if(!$layout) $layout = 'horizontal';
$menuItems = $menu->getData('menuItems');
$structure = json_decode($menu->getStructure(), true);
$items = [];
$html = '';
if(is_array($structure)){
	foreach ($structure as $k => $v) {
		$itemData = $data->renderMenuItemData($v, [], $menuItems);
		$html .= $data->drawItem($itemData);
	}
}
$mobileTemplate = $menu->getData("mobile_template");
if(!$mobileTemplate) $mobileTemplate = 1;
if($this->hasData("mobile_template")) $mobileTemplate = $this->getData("mobile_template");
$html = $data->filter($html);

$alias = $menu->getAlias().time().rand();
$disableBellow = (int)$menu->getData('disable_bellow');
$bodyClass = $class = '';
if($mobileTemplate == 0){
	$class = 'offcanvas-menu offcanvas-menu-left';
	$bodyClass = 'ves-offcanvas-menu-left';
}
if($mobileTemplate == 2){
	$class = 'accordion-menu';
	$bodyClass = 'ves-accordion-menu';
}
$desktopTemplate = $menu->getData("desktop_template");
if(!$desktopTemplate) $desktopTemplate = 'horizontal';
if($this->hasData("desktop_template")) $mobileTemplate = $this->getData("desktop_template");
$event = $menu->getData("event");
if(!$event) $event = 'hover';
if($this->hasData("event")) $event = $this->getData("event");
$id = time().rand();
$class = $menu->getData("classes");

$width = $menu->getWidth();
if(!$width) $width = '100%';
$width = 'style="width:' . $width . '"';
?>

<div class="block ves-menu <?php echo $class ?>" id="<?php echo $alias ?>-menu">
	<?php if($title = $this->getData("title")){ ?>
	<div class="block-title"><strong><span><?php echo __($title); ?></span></strong></div>
	<?php } ?>
	<?php // Off Canvas Menu ?>
	<?php if($mobileTemplate == 0){ ?>
	<div class="navbar navbar-inverse">
		<a href="javascript:;" class="ves-navbar-toggle <?php echo $alias ?>">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</a>
	</div>
	<?php } ?>
	<nav class="navigation" role="navigation">
		<ul id="<?php echo $alias ?>" <?php echo $width ?> class="ves-megamenu <?php echo 'menu-' . $event ?> ves-<?php echo $desktopTemplate ?>" <?php if($disableBellow>0){ ?>data-disable-bellow="<?php echo $disableBellow ?>"<?php } ?>>
			<?php echo $html; ?>
		</ul>
	</nav>
	<script type="text/javascript">
		require(['jquery',
			<?php if($menu->getData('scrolltofixed')){ ?>'Ves_Megamenu/js/jquery-scrolltofixed-min'<?php } ?>
			],function($){
				jQuery(document).ready(function($) {
					jQuery('#<?php echo $alias ?>-menu .ves-megamenu .level0').hover(function() {
						var mParent = jQuery(this).parents('.ves-megamenu').offset().top;
						var mHeight = jQuery(this).offset().top;
						var mTop    = (mHeight - mParent) + jQuery(this).height();
						jQuery(this).find('.submenu').first().css({top:mTop+"px"});
					});
					<?php if($menu->getData('scrolltofixed')){ ?>
						$(window).on("resize load", function(){
							if ($(window).width() >= 768){
								$('.sections.nav-sections').scrollToFixed();
							}else{
								if($('.sections.nav-sections').hasClass('.scroll-to-fixed-fixed')){
									$('.sections.nav-sections').trigger('detach.ScrollToFixed');
								}
								$('.sections.nav-sections').trigger('detach.ScrollToFixed');
							}
						});
						<?php } ?>
						jQuery('p').each(function() {
							var $this = $(this);
							if($this.html().replace(/\s|&nbsp;/g, '').length == 0)
							$this.remove();
						});
					});
				var menuToogle = function () {
					$('body').append('<div class="ves-overlay ves-overlay<?php echo $alias ?>"></div>');
					/*if ($('html').hasClass('nav-open')) {
						$('html').removeClass('nav-open');
						setTimeout(function () {
							$('html').removeClass('nav-before-open');
						}, 300);
					} else {
						$('html').addClass('nav-before-open');
						setTimeout(function () {
							$('html').addClass('nav-open');
						}, 42);
					}*/
				}
				$(document).on("click", ".action.nav-toggle", menuToogle);
				$("#<?php echo $alias ?> .dynamic-items li").hover(function(){
					$(this).parents(".dynamic-items").find("li").removeClass("dynamic-active");
					$(this).addClass("dynamic-active");
					var id = $(this).data("dynamic-id");
					$("#<?php echo $alias ?> ."+id).parent().find(".dynamic-item").removeClass("dynamic-active");
					$("#<?php echo $alias ?> ."+id).addClass("dynamic-active");
				});
				var mImg = '';
				$("#<?php echo $alias ?> img").hover(function(){
					mImg = '';
					mImg = $(this).attr('src');
					if($(this).data('hoverimg')){
						$(this).attr('src',$(this).data('hoverimg'));
					}
				},function(){
					$(this).attr('src',mImg);
				});
				$("#<?php echo $alias ?> li a").hover(function(){
					$(this).css({
						"background-color": $(this).data("hover-bgcolor"),
						"color": $(this).data("hover-color")
					});
				}, function(){
					$(this).css({
						"background-color": $(this).data("bgcolor"),
						"color": $(this).data("color")
					});
				});
				$(window).on("resize load", function(){
					if($("#<?php echo $alias ?>").data("disable-bellow")){
						if ($(window).width() <= $("#<?php echo $alias ?>").data("disable-bellow")){
							$("#<?php echo $alias ?>-menu").hide();
						}else{
							$("#<?php echo $alias ?>-menu").show();
						}
					}
					$("#<?php echo $alias ?>").find("li").each(function(index, element){
						if($(this).data("disable-bellow") && $(window).width() <= $(this).data("disable-bellow")){
							$(this).addClass("hidden");
						}else if($(this).hasClass("hidden")){
							$(this).removeClass("hidden");
						}
					});
					if ($(window).width() >= 800 && $(window).width() <= 1024){
						$("#<?php echo $alias ?> .nav-anchor").off().click(function(){
							var iParent = $(this).parent('li');
							iParent.addClass("clicked");
							if($(iParent).children('.submenu').length == 1){
								iParent.trigger('hover');
								if(iParent.hasClass('submenu-alignleft') || iParent.hasClass('submenu-alignright')){
									if((iParent.offset().left + iParent.find('.submenu').eq(0).width()) > $(window).width()){
										iParent.find('.submenu').eq(0).css('max-width','100%');
										iParent.css('position','static');
									}
								}
								return false;
							}
						});
					}else{
						$("#<?php echo $alias ?>").find('.submenu').css('max-width','');
						$("#<?php echo $alias ?>").find('.submenu-alignleft').css('position','relative');
					}
					if ($(window).width() <= 800){
						$('.sections.nav-sections').removeAttr( "style" )
						$("#<?php echo $alias ?>").addClass("nav-mobile");
					}else{
						$("#<?php echo $alias ?>").find(".submenu").css({'display':''});
						$("#<?php echo $alias ?>").find("div").removeClass("mbactive");
						$("#<?php echo $alias ?>").removeClass("nav-mobile");
					}
				}).resize();
				$('#<?php echo $alias ?> .opener').on('click', function(e) {
					e.preventDefault();
					$("#<?php echo $alias ?> .nav-item").removeClass("item-active");
					var parent = $(this).parents(".nav-item").eq(0);
					$(this).toggleClass('item-active');
					$(parent).find(".submenu").eq(0).stop().slideToggle();
					return false;	
				});
				/*$(document).on("click", ".ves-overlay<?php echo $alias ?>", function(){
					$('#<?php echo $alias ?>').css("left","");
					$('html').removeClass('nav-open');
					setTimeout(function () {
						$('html').removeClass('nav-before-open');
					}, 300);
					$(this).remove();
					return false;
				});*/

				// $(document).on("click", "div", function(){
				// 	alert("abc");
				// });
			});
		</script>
	</div>
	<?php } ?>