
    <p id="back-top" style="display: none;"><a title="<?php echo __('Top')?>" href="#top"><?php echo __('Top')?></a></p>
	<script type="text/javascript">
    //<![CDATA[
    require([
    'jquery'
    ], function($){
     var sBackTop = $('#back-top');
                if(sBackTop.length){
                    //var sClickBackTop = $('#back-top a');
                    sBackTop.hide();
                    // fade in #back-top

                        $(window).scroll(function() {
                            if ($(this).scrollTop() > 100) {
                                sBackTop.fadeIn();
                            } else {
                                sBackTop.fadeOut();
                            }
                        });
                        // scroll body to 0px on click
                        $('a', sBackTop).click(function() {
                            $('body,html').animate({
                                scrollTop: 0
                            }, 800);
                            return false;
                        });
                    
                }

        $("body").addClass( "full-main-column" );
        if( $('div.sidebar.sidebar-main').length )
            {
                $("body").removeClass( "full-main-column" );
            }
    });
        
    //]]>
    </script>
	
	
	<script type="text/javascript">
	requirejs(['jquery','listnavpagination'], function($){
		jQuery(document).ready(function($) {
            $('.navigation li.level0 .submenu.dropdown-menu.animated .content-wrap .megamenu-content .level1.nav-dropdown').each(function(i) {
				$(this).attr('id', 'row-wrapper' + i);
			});
			$('#row-wrapper0').listnav({
				includeNums: false,
			});
			$('#row-wrapper2').listnav({
				includeNums: false,
			});
		});
	});
	requirejs(['listnavfilter'], function($){
		jQuery(document).ready(function($) {
			$('.nav-brands .submenu.dropdown-menu .content-wrap .megamenu-content .level1.nav-dropdown').lookingfor({
				input: $('input[name="query"]'),
				items: 'div.row'
			});
            $('.category-boutiqaat-celebrities .filter-options-content').lookingfor({
				input: $('input[name="filterquery"]'),
				items: 'li.item'
			});
            $('.category-boutiqaat-celebrities .filter-options-content').lookingfor({
				input: $('input[name="filterquerymobile"]'),
				items: 'li.item'
			});
		});
	});
	
    </script>
	